services:
  postgres:
    image: postgres:15-alpine
    container_name: netdog-postgres
    environment:
      POSTGRES_DB: netdog
      POSTGRES_USER: netdog
      POSTGRES_PASSWORD: netdog
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U netdog"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: netdog-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: netdog-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    network_mode: "host"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://netdog:netdog@localhost:5432/netdog
      - REDIS_URL=redis://localhost:6379/0
      - SECRET_KEY=dev-secret-key-change-in-production
      - ENVIRONMENT=development
    cap_add:
      - NET_ADMIN
      - NET_RAW

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: netdog-worker
    command: celery -A app.worker worker --loglevel=info --concurrency=4
    network_mode: "host"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://netdog:netdog@localhost:5432/netdog
      - REDIS_URL=redis://localhost:6379/0
      - SECRET_KEY=dev-secret-key-change-in-production
      - ENVIRONMENT=development
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    cap_add:
      - NET_ADMIN
      - NET_RAW

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: netdog-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_WS_URL=ws://localhost:8000
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data:
